// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: deepspan/v1/device.proto

package deepspanv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/myorg/deepspan/l5-gen/go/deepspan/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HwipServiceName is the fully-qualified name of the HwipService service.
	HwipServiceName = "deepspan.v1.HwipService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HwipServiceListDevicesProcedure is the fully-qualified name of the HwipService's ListDevices RPC.
	HwipServiceListDevicesProcedure = "/deepspan.v1.HwipService/ListDevices"
	// HwipServiceGetDeviceStatusProcedure is the fully-qualified name of the HwipService's
	// GetDeviceStatus RPC.
	HwipServiceGetDeviceStatusProcedure = "/deepspan.v1.HwipService/GetDeviceStatus"
	// HwipServiceSubmitRequestProcedure is the fully-qualified name of the HwipService's SubmitRequest
	// RPC.
	HwipServiceSubmitRequestProcedure = "/deepspan.v1.HwipService/SubmitRequest"
	// HwipServiceStreamEventsProcedure is the fully-qualified name of the HwipService's StreamEvents
	// RPC.
	HwipServiceStreamEventsProcedure = "/deepspan.v1.HwipService/StreamEvents"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	hwipServiceServiceDescriptor               = v1.File_deepspan_v1_device_proto.Services().ByName("HwipService")
	hwipServiceListDevicesMethodDescriptor     = hwipServiceServiceDescriptor.Methods().ByName("ListDevices")
	hwipServiceGetDeviceStatusMethodDescriptor = hwipServiceServiceDescriptor.Methods().ByName("GetDeviceStatus")
	hwipServiceSubmitRequestMethodDescriptor   = hwipServiceServiceDescriptor.Methods().ByName("SubmitRequest")
	hwipServiceStreamEventsMethodDescriptor    = hwipServiceServiceDescriptor.Methods().ByName("StreamEvents")
)

// HwipServiceClient is a client for the deepspan.v1.HwipService service.
type HwipServiceClient interface {
	// List devices
	ListDevices(context.Context, *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error)
	// Get device status
	GetDeviceStatus(context.Context, *connect.Request[v1.GetDeviceStatusRequest]) (*connect.Response[v1.GetDeviceStatusResponse], error)
	// Submit request (async, io_uring-based)
	SubmitRequest(context.Context, *connect.Request[v1.SubmitRequestRequest]) (*connect.Response[v1.SubmitRequestResponse], error)
	// Event streaming (server-side streaming)
	StreamEvents(context.Context, *connect.Request[v1.StreamEventsRequest]) (*connect.ServerStreamForClient[v1.DeviceEvent], error)
}

// NewHwipServiceClient constructs a client for the deepspan.v1.HwipService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHwipServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HwipServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &hwipServiceClient{
		listDevices: connect.NewClient[v1.ListDevicesRequest, v1.ListDevicesResponse](
			httpClient,
			baseURL+HwipServiceListDevicesProcedure,
			connect.WithSchema(hwipServiceListDevicesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDeviceStatus: connect.NewClient[v1.GetDeviceStatusRequest, v1.GetDeviceStatusResponse](
			httpClient,
			baseURL+HwipServiceGetDeviceStatusProcedure,
			connect.WithSchema(hwipServiceGetDeviceStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		submitRequest: connect.NewClient[v1.SubmitRequestRequest, v1.SubmitRequestResponse](
			httpClient,
			baseURL+HwipServiceSubmitRequestProcedure,
			connect.WithSchema(hwipServiceSubmitRequestMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		streamEvents: connect.NewClient[v1.StreamEventsRequest, v1.DeviceEvent](
			httpClient,
			baseURL+HwipServiceStreamEventsProcedure,
			connect.WithSchema(hwipServiceStreamEventsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// hwipServiceClient implements HwipServiceClient.
type hwipServiceClient struct {
	listDevices     *connect.Client[v1.ListDevicesRequest, v1.ListDevicesResponse]
	getDeviceStatus *connect.Client[v1.GetDeviceStatusRequest, v1.GetDeviceStatusResponse]
	submitRequest   *connect.Client[v1.SubmitRequestRequest, v1.SubmitRequestResponse]
	streamEvents    *connect.Client[v1.StreamEventsRequest, v1.DeviceEvent]
}

// ListDevices calls deepspan.v1.HwipService.ListDevices.
func (c *hwipServiceClient) ListDevices(ctx context.Context, req *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error) {
	return c.listDevices.CallUnary(ctx, req)
}

// GetDeviceStatus calls deepspan.v1.HwipService.GetDeviceStatus.
func (c *hwipServiceClient) GetDeviceStatus(ctx context.Context, req *connect.Request[v1.GetDeviceStatusRequest]) (*connect.Response[v1.GetDeviceStatusResponse], error) {
	return c.getDeviceStatus.CallUnary(ctx, req)
}

// SubmitRequest calls deepspan.v1.HwipService.SubmitRequest.
func (c *hwipServiceClient) SubmitRequest(ctx context.Context, req *connect.Request[v1.SubmitRequestRequest]) (*connect.Response[v1.SubmitRequestResponse], error) {
	return c.submitRequest.CallUnary(ctx, req)
}

// StreamEvents calls deepspan.v1.HwipService.StreamEvents.
func (c *hwipServiceClient) StreamEvents(ctx context.Context, req *connect.Request[v1.StreamEventsRequest]) (*connect.ServerStreamForClient[v1.DeviceEvent], error) {
	return c.streamEvents.CallServerStream(ctx, req)
}

// HwipServiceHandler is an implementation of the deepspan.v1.HwipService service.
type HwipServiceHandler interface {
	// List devices
	ListDevices(context.Context, *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error)
	// Get device status
	GetDeviceStatus(context.Context, *connect.Request[v1.GetDeviceStatusRequest]) (*connect.Response[v1.GetDeviceStatusResponse], error)
	// Submit request (async, io_uring-based)
	SubmitRequest(context.Context, *connect.Request[v1.SubmitRequestRequest]) (*connect.Response[v1.SubmitRequestResponse], error)
	// Event streaming (server-side streaming)
	StreamEvents(context.Context, *connect.Request[v1.StreamEventsRequest], *connect.ServerStream[v1.DeviceEvent]) error
}

// NewHwipServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHwipServiceHandler(svc HwipServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	hwipServiceListDevicesHandler := connect.NewUnaryHandler(
		HwipServiceListDevicesProcedure,
		svc.ListDevices,
		connect.WithSchema(hwipServiceListDevicesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	hwipServiceGetDeviceStatusHandler := connect.NewUnaryHandler(
		HwipServiceGetDeviceStatusProcedure,
		svc.GetDeviceStatus,
		connect.WithSchema(hwipServiceGetDeviceStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	hwipServiceSubmitRequestHandler := connect.NewUnaryHandler(
		HwipServiceSubmitRequestProcedure,
		svc.SubmitRequest,
		connect.WithSchema(hwipServiceSubmitRequestMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	hwipServiceStreamEventsHandler := connect.NewServerStreamHandler(
		HwipServiceStreamEventsProcedure,
		svc.StreamEvents,
		connect.WithSchema(hwipServiceStreamEventsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/deepspan.v1.HwipService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HwipServiceListDevicesProcedure:
			hwipServiceListDevicesHandler.ServeHTTP(w, r)
		case HwipServiceGetDeviceStatusProcedure:
			hwipServiceGetDeviceStatusHandler.ServeHTTP(w, r)
		case HwipServiceSubmitRequestProcedure:
			hwipServiceSubmitRequestHandler.ServeHTTP(w, r)
		case HwipServiceStreamEventsProcedure:
			hwipServiceStreamEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHwipServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHwipServiceHandler struct{}

func (UnimplementedHwipServiceHandler) ListDevices(context.Context, *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deepspan.v1.HwipService.ListDevices is not implemented"))
}

func (UnimplementedHwipServiceHandler) GetDeviceStatus(context.Context, *connect.Request[v1.GetDeviceStatusRequest]) (*connect.Response[v1.GetDeviceStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deepspan.v1.HwipService.GetDeviceStatus is not implemented"))
}

func (UnimplementedHwipServiceHandler) SubmitRequest(context.Context, *connect.Request[v1.SubmitRequestRequest]) (*connect.Response[v1.SubmitRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deepspan.v1.HwipService.SubmitRequest is not implemented"))
}

func (UnimplementedHwipServiceHandler) StreamEvents(context.Context, *connect.Request[v1.StreamEventsRequest], *connect.ServerStream[v1.DeviceEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("deepspan.v1.HwipService.StreamEvents is not implemented"))
}
