# deepspan firmware default configuration
CONFIG_DEEPSPAN_FIRMWARE=y
CONFIG_DEEPSPAN_USE_ETL=y
CONFIG_DEEPSPAN_USE_CIB=y

# Zephyr default configuration
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_PRINTK=y

# C++ configuration — CIB requires C++20
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# virtio/RPMsg (enable on real HW)
# CONFIG_DEEPSPAN_TRANSPORT_VIRTIO=y
# CONFIG_VIRTIO=y
# CONFIG_RPMSG=y
# CONFIG_OPENAMP=y
