# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from deepspan.v1 import device_pb2 as deepspan_dot_v1_dot_device__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in deepspan/v1/device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HwipServiceStub(object):
    """HwipService: Hardware IP device control service
    Provides gRPC + gRPC-Web + REST on a single port via ConnectRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/deepspan.v1.HwipService/ListDevices',
                request_serializer=deepspan_dot_v1_dot_device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_device__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatus = channel.unary_unary(
                '/deepspan.v1.HwipService/GetDeviceStatus',
                request_serializer=deepspan_dot_v1_dot_device__pb2.GetDeviceStatusRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_device__pb2.GetDeviceStatusResponse.FromString,
                _registered_method=True)
        self.SubmitRequest = channel.unary_unary(
                '/deepspan.v1.HwipService/SubmitRequest',
                request_serializer=deepspan_dot_v1_dot_device__pb2.SubmitRequestRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_device__pb2.SubmitRequestResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/deepspan.v1.HwipService/StreamEvents',
                request_serializer=deepspan_dot_v1_dot_device__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_device__pb2.DeviceEvent.FromString,
                _registered_method=True)


class HwipServiceServicer(object):
    """HwipService: Hardware IP device control service
    Provides gRPC + gRPC-Web + REST on a single port via ConnectRPC
    """

    def ListDevices(self, request, context):
        """List devices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatus(self, request, context):
        """Get device status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitRequest(self, request, context):
        """Submit request (async, io_uring-based)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Event streaming (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HwipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=deepspan_dot_v1_dot_device__pb2.ListDevicesRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatus,
                    request_deserializer=deepspan_dot_v1_dot_device__pb2.GetDeviceStatusRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_device__pb2.GetDeviceStatusResponse.SerializeToString,
            ),
            'SubmitRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRequest,
                    request_deserializer=deepspan_dot_v1_dot_device__pb2.SubmitRequestRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_device__pb2.SubmitRequestResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=deepspan_dot_v1_dot_device__pb2.StreamEventsRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_device__pb2.DeviceEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deepspan.v1.HwipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deepspan.v1.HwipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HwipService(object):
    """HwipService: Hardware IP device control service
    Provides gRPC + gRPC-Web + REST on a single port via ConnectRPC
    """

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.HwipService/ListDevices',
            deepspan_dot_v1_dot_device__pb2.ListDevicesRequest.SerializeToString,
            deepspan_dot_v1_dot_device__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.HwipService/GetDeviceStatus',
            deepspan_dot_v1_dot_device__pb2.GetDeviceStatusRequest.SerializeToString,
            deepspan_dot_v1_dot_device__pb2.GetDeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.HwipService/SubmitRequest',
            deepspan_dot_v1_dot_device__pb2.SubmitRequestRequest.SerializeToString,
            deepspan_dot_v1_dot_device__pb2.SubmitRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/deepspan.v1.HwipService/StreamEvents',
            deepspan_dot_v1_dot_device__pb2.StreamEventsRequest.SerializeToString,
            deepspan_dot_v1_dot_device__pb2.DeviceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
