# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deepspan/v1/management.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'deepspan/v1/management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64\x65\x65pspan/v1/management.proto\x12\x0b\x64\x65\x65pspan.v1\"+\n\x16GetFirmwareInfoRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"m\n\x17GetFirmwareInfoResponse\x12\x12\n\nfw_version\x18\x01 \x01(\t\x12\x12\n\nbuild_date\x18\x02 \x01(\t\x12\x18\n\x10protocol_version\x18\x03 \x01(\r\x12\x10\n\x08\x66\x65\x61tures\x18\x04 \x03(\t\"6\n\x12ResetDeviceRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05\x66orce\x18\x02 \x01(\x08\"7\n\x13ResetDeviceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x91\x01\n\x11PushConfigRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12:\n\x06\x63onfig\x18\x02 \x03(\x0b\x32*.deepspan.v1.PushConfigRequest.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x12PushConfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rrejected_keys\x18\x02 \x03(\t\"*\n\x15GetConsolePathRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"*\n\x16GetConsolePathResponse\x12\x10\n\x08pty_path\x18\x01 \x01(\t2\xed\x02\n\x11ManagementService\x12\\\n\x0fGetFirmwareInfo\x12#.deepspan.v1.GetFirmwareInfoRequest\x1a$.deepspan.v1.GetFirmwareInfoResponse\x12P\n\x0bResetDevice\x12\x1f.deepspan.v1.ResetDeviceRequest\x1a .deepspan.v1.ResetDeviceResponse\x12M\n\nPushConfig\x12\x1e.deepspan.v1.PushConfigRequest\x1a\x1f.deepspan.v1.PushConfigResponse\x12Y\n\x0eGetConsolePath\x12\".deepspan.v1.GetConsolePathRequest\x1a#.deepspan.v1.GetConsolePathResponseB9Z7github.com/myorg/deepspan/gen/go/deepspan/v1;deepspanv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deepspan.v1.management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/myorg/deepspan/gen/go/deepspan/v1;deepspanv1'
  _globals['_PUSHCONFIGREQUEST_CONFIGENTRY']._loaded_options = None
  _globals['_PUSHCONFIGREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_GETFIRMWAREINFOREQUEST']._serialized_start=45
  _globals['_GETFIRMWAREINFOREQUEST']._serialized_end=88
  _globals['_GETFIRMWAREINFORESPONSE']._serialized_start=90
  _globals['_GETFIRMWAREINFORESPONSE']._serialized_end=199
  _globals['_RESETDEVICEREQUEST']._serialized_start=201
  _globals['_RESETDEVICEREQUEST']._serialized_end=255
  _globals['_RESETDEVICERESPONSE']._serialized_start=257
  _globals['_RESETDEVICERESPONSE']._serialized_end=312
  _globals['_PUSHCONFIGREQUEST']._serialized_start=315
  _globals['_PUSHCONFIGREQUEST']._serialized_end=460
  _globals['_PUSHCONFIGREQUEST_CONFIGENTRY']._serialized_start=415
  _globals['_PUSHCONFIGREQUEST_CONFIGENTRY']._serialized_end=460
  _globals['_PUSHCONFIGRESPONSE']._serialized_start=462
  _globals['_PUSHCONFIGRESPONSE']._serialized_end=522
  _globals['_GETCONSOLEPATHREQUEST']._serialized_start=524
  _globals['_GETCONSOLEPATHREQUEST']._serialized_end=566
  _globals['_GETCONSOLEPATHRESPONSE']._serialized_start=568
  _globals['_GETCONSOLEPATHRESPONSE']._serialized_end=610
  _globals['_MANAGEMENTSERVICE']._serialized_start=613
  _globals['_MANAGEMENTSERVICE']._serialized_end=978
# @@protoc_insertion_point(module_scope)
