# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from deepspan.v1 import management_pb2 as deepspan_dot_v1_dot_management__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in deepspan/v1/management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementServiceStub(object):
    """ManagementService: Firmware lifecycle and management service
    Communicates with firmware over OpenAMP channel via mgmt-daemon
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFirmwareInfo = channel.unary_unary(
                '/deepspan.v1.ManagementService/GetFirmwareInfo',
                request_serializer=deepspan_dot_v1_dot_management__pb2.GetFirmwareInfoRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_management__pb2.GetFirmwareInfoResponse.FromString,
                _registered_method=True)
        self.ResetDevice = channel.unary_unary(
                '/deepspan.v1.ManagementService/ResetDevice',
                request_serializer=deepspan_dot_v1_dot_management__pb2.ResetDeviceRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_management__pb2.ResetDeviceResponse.FromString,
                _registered_method=True)
        self.PushConfig = channel.unary_unary(
                '/deepspan.v1.ManagementService/PushConfig',
                request_serializer=deepspan_dot_v1_dot_management__pb2.PushConfigRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_management__pb2.PushConfigResponse.FromString,
                _registered_method=True)
        self.GetConsolePath = channel.unary_unary(
                '/deepspan.v1.ManagementService/GetConsolePath',
                request_serializer=deepspan_dot_v1_dot_management__pb2.GetConsolePathRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_management__pb2.GetConsolePathResponse.FromString,
                _registered_method=True)


class ManagementServiceServicer(object):
    """ManagementService: Firmware lifecycle and management service
    Communicates with firmware over OpenAMP channel via mgmt-daemon
    """

    def GetFirmwareInfo(self, request, context):
        """Get firmware info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDevice(self, request, context):
        """Restart device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushConfig(self, request, context):
        """Push runtime configuration (Linux → Zephyr, rpmsg-config channel)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsolePath(self, request, context):
        """Get console PTY path (OpenAMP proxy)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFirmwareInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFirmwareInfo,
                    request_deserializer=deepspan_dot_v1_dot_management__pb2.GetFirmwareInfoRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_management__pb2.GetFirmwareInfoResponse.SerializeToString,
            ),
            'ResetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDevice,
                    request_deserializer=deepspan_dot_v1_dot_management__pb2.ResetDeviceRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_management__pb2.ResetDeviceResponse.SerializeToString,
            ),
            'PushConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PushConfig,
                    request_deserializer=deepspan_dot_v1_dot_management__pb2.PushConfigRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_management__pb2.PushConfigResponse.SerializeToString,
            ),
            'GetConsolePath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsolePath,
                    request_deserializer=deepspan_dot_v1_dot_management__pb2.GetConsolePathRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_management__pb2.GetConsolePathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deepspan.v1.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deepspan.v1.ManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """ManagementService: Firmware lifecycle and management service
    Communicates with firmware over OpenAMP channel via mgmt-daemon
    """

    @staticmethod
    def GetFirmwareInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.ManagementService/GetFirmwareInfo',
            deepspan_dot_v1_dot_management__pb2.GetFirmwareInfoRequest.SerializeToString,
            deepspan_dot_v1_dot_management__pb2.GetFirmwareInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.ManagementService/ResetDevice',
            deepspan_dot_v1_dot_management__pb2.ResetDeviceRequest.SerializeToString,
            deepspan_dot_v1_dot_management__pb2.ResetDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.ManagementService/PushConfig',
            deepspan_dot_v1_dot_management__pb2.PushConfigRequest.SerializeToString,
            deepspan_dot_v1_dot_management__pb2.PushConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsolePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.ManagementService/GetConsolePath',
            deepspan_dot_v1_dot_management__pb2.GetConsolePathRequest.SerializeToString,
            deepspan_dot_v1_dot_management__pb2.GetConsolePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
