# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from deepspan.v1 import telemetry_pb2 as deepspan_dot_v1_dot_telemetry__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in deepspan/v1/telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """TelemetryService: Real-time telemetry collection service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTelemetry = channel.unary_unary(
                '/deepspan.v1.TelemetryService/GetTelemetry',
                request_serializer=deepspan_dot_v1_dot_telemetry__pb2.GetTelemetryRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_telemetry__pb2.GetTelemetryResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.unary_stream(
                '/deepspan.v1.TelemetryService/StreamTelemetry',
                request_serializer=deepspan_dot_v1_dot_telemetry__pb2.StreamTelemetryRequest.SerializeToString,
                response_deserializer=deepspan_dot_v1_dot_telemetry__pb2.TelemetrySnapshot.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """TelemetryService: Real-time telemetry collection service
    """

    def GetTelemetry(self, request, context):
        """Get telemetry snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request, context):
        """Real-time telemetry streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=deepspan_dot_v1_dot_telemetry__pb2.GetTelemetryRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_telemetry__pb2.GetTelemetryResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=deepspan_dot_v1_dot_telemetry__pb2.StreamTelemetryRequest.FromString,
                    response_serializer=deepspan_dot_v1_dot_telemetry__pb2.TelemetrySnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deepspan.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deepspan.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """TelemetryService: Real-time telemetry collection service
    """

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deepspan.v1.TelemetryService/GetTelemetry',
            deepspan_dot_v1_dot_telemetry__pb2.GetTelemetryRequest.SerializeToString,
            deepspan_dot_v1_dot_telemetry__pb2.GetTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/deepspan.v1.TelemetryService/StreamTelemetry',
            deepspan_dot_v1_dot_telemetry__pb2.StreamTelemetryRequest.SerializeToString,
            deepspan_dot_v1_dot_telemetry__pb2.TelemetrySnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
