# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deepspan/v1/telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'deepspan/v1/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x65\x65pspan/v1/telemetry.proto\x12\x0b\x64\x65\x65pspan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n\x13GetTelemetryRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"H\n\x14GetTelemetryResponse\x12\x30\n\x08snapshot\x18\x01 \x01(\x0b\x32\x1e.deepspan.v1.TelemetrySnapshot\"@\n\x16StreamTelemetryRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0binterval_ms\x18\x02 \x01(\r\"\xb5\x01\n\x11TelemetrySnapshot\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x08\x66irmware\x18\x03 \x01(\x0b\x32\x1e.deepspan.v1.FirmwareTelemetry\x12,\n\x06kernel\x18\x04 \x01(\x0b\x32\x1c.deepspan.v1.KernelTelemetry\"\x9a\x01\n\x11\x46irmwareTelemetry\x12\x15\n\rcpu_usage_pct\x18\x01 \x01(\r\x12\x17\n\x0fheap_free_bytes\x18\x02 \x01(\r\x12\x18\n\x10stack_free_bytes\x18\x03 \x01(\r\x12\x11\n\tuptime_ms\x18\x04 \x01(\r\x12(\n\x07threads\x18\x05 \x03(\x0b\x32\x17.deepspan.v1.ThreadInfo\"O\n\nThreadInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\r\x12\r\n\x05state\x18\x03 \x01(\t\x12\x12\n\nstack_used\x18\x04 \x01(\r\"_\n\x0fKernelTelemetry\x12\x11\n\tirq_count\x18\x01 \x01(\x04\x12\x11\n\tdma_bytes\x18\x02 \x01(\x04\x12\x10\n\x08vq_depth\x18\x03 \x01(\r\x12\x14\n\x0cpending_cmds\x18\x04 \x01(\r2\xc1\x01\n\x10TelemetryService\x12S\n\x0cGetTelemetry\x12 .deepspan.v1.GetTelemetryRequest\x1a!.deepspan.v1.GetTelemetryResponse\x12X\n\x0fStreamTelemetry\x12#.deepspan.v1.StreamTelemetryRequest\x1a\x1e.deepspan.v1.TelemetrySnapshot0\x01\x42\x39Z7github.com/myorg/deepspan/gen/go/deepspan/v1;deepspanv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deepspan.v1.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/myorg/deepspan/gen/go/deepspan/v1;deepspanv1'
  _globals['_GETTELEMETRYREQUEST']._serialized_start=77
  _globals['_GETTELEMETRYREQUEST']._serialized_end=117
  _globals['_GETTELEMETRYRESPONSE']._serialized_start=119
  _globals['_GETTELEMETRYRESPONSE']._serialized_end=191
  _globals['_STREAMTELEMETRYREQUEST']._serialized_start=193
  _globals['_STREAMTELEMETRYREQUEST']._serialized_end=257
  _globals['_TELEMETRYSNAPSHOT']._serialized_start=260
  _globals['_TELEMETRYSNAPSHOT']._serialized_end=441
  _globals['_FIRMWARETELEMETRY']._serialized_start=444
  _globals['_FIRMWARETELEMETRY']._serialized_end=598
  _globals['_THREADINFO']._serialized_start=600
  _globals['_THREADINFO']._serialized_end=679
  _globals['_KERNELTELEMETRY']._serialized_start=681
  _globals['_KERNELTELEMETRY']._serialized_end=776
  _globals['_TELEMETRYSERVICE']._serialized_start=779
  _globals['_TELEMETRYSERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
